spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invoice
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
      enable_lazy_load_no_trans: true
    defer-datasource-initialization: true
    show_sql: true

  sql:
    init:
      mode: always


