spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invoice
    username: postgres
    password: postgres

  jackson:
    time-zone: UTC

  jpa:
    hibernate:
      ddl-auto: update
      enable_lazy_load_no_trans: true
    show_sql: false

  sql:
    init:
      mode: always

  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  web:
    resources:
      static-locations:
        - "file:src/main/resources/static/"
        - "classpath:/static/"

server:
  error:
    whitelabel:
      enabled: false
    path: /error

